### ISSUE TITLE
Clarification on the Use of video_projection_scalar in Feature Scaling

### ISSUE THREAD

**Issue by nguyenvulebinh** [roudimit/whisper-flamingo#3]
I noticed the following [code snippet](https://github.com/roudimit/whisper-flamingo/blob/cda922a7dc4831f5bcb4ed694f20673cffa19dae/whisper/model.py#L230) in your implementation:

```python
x_v = self.video_projection(x_v)
x_v = self.video_projection_scalar * x_v
```

Where self.video_projection is a linear layer, and self.video_projection_scalar is a learnable parameter initialized as nn.Parameter(torch.tensor(1.)). 

I was wondering if you could clarify the motivation behind using the video_projection_scalar here.

**Comment by roudimit** [comment]
Thanks for your interest! In the beginning of this project, I tried simple fusion methods such as early fusion. This was implemented with the code you referenced, then adding the embeddings with the Whisper audio embeddings before Whisper's transformer encoder. The motivation of `self.video_projection_scalar` was to allow the model to adjust the scale / norm of the video embeddings to match the scale / norm of the audio embeddings (for more effective processing by Whisper's encoder). In the end, early fusion didn't work well and I switched to gated cross attention. I didn't remove `self.video_projection_scalar`, so now it's part of the model.
