### ISSUE TITLE
AV-HuBERT issues coming up when using this model

### ISSUE THREAD

**Issue by aristosp** [roudimit/whisper-flamingo#4]
Hello and thank you for your code. I have a few things to mention, as I am trying to experiment on your code. First of all, it should be mentioned that the following versions must be followed in order to use AV-HuBERT:
```
pip==24.0 omegaconf==2.0.4  hydra-core==1.0.7 
```
Secondly, when trying to adapt the code provided from the example, the following error arises:
```
ValueError: Cannot register duplicate task (av_hubert_pretraining)
```
Which again is something that derives from AV-Hubert.

**Comment by roudimit** [comment]
Hi, thanks for your interest! Yes, it seems that pip needs to be downgraded to pip==24.0. This can be done with: 
```
python -m pip install pip==24.0
pip --version
``` 
For the AV-HuBERT problem, I haven't experienced that before. Can you explain which command you are running exactly and post the stack trace? Also, it seems that someone else experienced this problem in the [AV-HuBERT issues](https://github.com/facebookresearch/av_hubert/issues/36). 

Finally, I just tested one of my [Google Colab demos](https://colab.research.google.com/drive/1rnhNOZuUxh-WXXloo_z1fu5DKeJrH95p), and it worked fine. 

My best guest is that something is wrong with the AV-HuBERT path, but if you provide more info maybe we can figure it out together.

**Comment by aristosp** [comment]
Hello, thank you for the instant reply. So far I have solved with the AV-HuBERT issue when trying to run seperately AV-HuBERT, after doing a clean installation. I think I'll do the same for Whisper-flamingo and come back to this if it doesn't work out.

**Comment by aristosp** [comment]
Update: I think it's a directory issue. I am trying to run the demo code provided in the colab, adapted to my own PC, but I get the same error. Also, I think in the colab you don't install AV-HuBERTs requirements, which I thought might be the reason why colab notebook works and local run does not, but unfortunately I don't think that is the case.

**Comment by roudimit** [comment]
Thanks for the update! I have not experienced that problem before. If you could post the command you're running / the solution, that would probably be helpful for myself and others in the future.

**Comment by aristosp** [comment]
To be honest, I just moved around and played with the directories. Adding 
``` 
sys.path.insert(0, 'path_to_avhubert') 
sys.path.insert(0, 'path_to_fairseq')
```
Definitely helps, also changing imports is very helpful as well. Since it's a directory issue, you habe to play around with the directories. Many thanks for the responses and for the good work of course.
